import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is fully autogenerated: the three hand-written pages carry
// frontmatter sidebar_position values, and website/sync-reference.mjs emits
// docs/reference/ (one page per README `##` section + _category_.json) with
// its own ordering. Adding a section to the README grows the sidebar.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
